let design = "xxxxxxxxxxxxxxxxxxxxxx";
let blank = "                     x";
let marksheet = "Marksheet            x";
let name = "Name = Shubham Pal   x";
let school = "School = CBSE        x";
let roll = "Roll No. = 77        x";
let grade = "Grade = 12th         x";
let section = "Section = A          x";
let marks = "Subject Marks        x";
let hindi = "Hindi = 92           x";
let english = "English = 94         x";
let science = "Science = 96         x";
let space = "                     x";
let footer = "xxxxxxxxxxxxxxxxxxxxxx";
console.log(design);
console.log(blank);
console.log(marksheet);
console.log(name);
console.log(school);
console.log(roll);
console.log(grade);
console.log(section);
console.log(marks);
console.log(hindi);
console.log(english);
console.log(science);
console.log(space);
console.log(footer);

